### ISSUE TITLE
Text in table heading is cut off at the bottom

### ISSUE THREAD

**Issue by jisensee** [jisensee/adalia.info#9]
Letters like 'y' get cut off at the bottom of the table header. Needs some CSS fiddling.

**Comment by kelleygrace88** [comment]
@jisensee Can I please take this if it's not already assigned?

**Comment by jisensee** [comment]
> @jisensee Can I please take this if it's not already assigned?

Sure go for it! Probably needs some adjustment in [datatable.css](https://github.com/jisensee/adalia.info/blob/f0be9f85589ab0015b64be64eb6b03efa0eb6551/client/src/css/datatable.css), but I am not 100% sure yet what exactly the issue is.

**Comment by jisensee** [comment]
Actually found the issue while doing some other work on the table. Line-height was simply too small, probably because of custom font.

**Comment by kelleygrace88** [comment]
Nice! I tried adjusting line-height by putting "@apply leading-10" under ".rdt_TableCol_Sortable" in datatable.css, but nothing changed.... did you do something similar?

**Comment by kelleygrace88** [comment]
Oh! Just had to add "!important"

**Comment by jisensee** [comment]
Yea, did the same (8 was enough though). Sorry to beat you to it.

**Comment by jisensee** [comment]
fixed in #22
